import React from 'react';
import { RFP } from '../../types';
import SummaryCard from './SummaryCard';
import RequirementBreakdown from './RequirementBreakdown';
import StrategyView from './StrategyView';

interface FullReportTemplateProps {
    rfp: RFP;
    id?: string;
}

const FullReportTemplate: React.FC<FullReportTemplateProps> = ({ rfp, id }) => {
    if (!rfp.structuredAnalysis) return null;

    return (
        <div
            id={id}
            className="bg-white p-8 w-[210mm] min-h-[297mm] mx-auto absolute top-0 left-[-9999px]"
            style={{ width: '800px' }} // Fixed width for consistent PDF capability
        >
            <div className="space-y-8">
                {/* Header */}
                <div className="border-b-2 border-indigo-600 pb-4 mb-8">
                    <h1 className="text-3xl font-bold text-gray-900">{rfp.structuredAnalysis.summary.project_name}</h1>
                    <p className="text-indigo-600 font-bold mt-2">AI 정밀 분석 리포트</p>
                    <p className="text-gray-400 text-xs mt-1">분석일: {rfp.analysisDate} | 문서번호: {rfp.id}</p>
                </div>

                {/* Section 1: Summary */}
                <section>
                    <h2 className="text-xl font-bold bg-indigo-50 p-2 border-l-4 border-indigo-600 mb-4 text-indigo-900">
                        1. 프로젝트 요약
                    </h2>
                    <SummaryCard summary={rfp.structuredAnalysis.summary} />
                </section>

                <div className="h-4"></div>

                {/* Section 2: Requirements */}
                <section>
                    <h2 className="text-xl font-bold bg-indigo-50 p-2 border-l-4 border-indigo-600 mb-4 text-indigo-900">
                        2. 요구사항 상세 분석
                    </h2>
                    <RequirementBreakdown requirements={rfp.structuredAnalysis.requirements} />
                </section>

                <div className="h-4"></div>

                {/* Section 3: Strategy */}
                <section>
                    <h2 className="text-xl font-bold bg-indigo-50 p-2 border-l-4 border-indigo-600 mb-4 text-indigo-900">
                        3. 수주/제안 전략
                    </h2>
                    <StrategyView strategy={rfp.structuredAnalysis.strategy} />
                </section>

                {/* Footer */}
                <div className="mt-12 pt-4 border-t border-gray-100 text-center text-gray-400 text-xs">
                    Generated by NaraStore Analytics AI
                </div>
            </div>
        </div>
    );
};

export default FullReportTemplate;
